# Generated by Django 3.2.5 on 2022-03-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponrules', '0002_auto_20220313_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='loyalty_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='couponrules.loyaltystatusrule', verbose_name='Loyalty Points rule'),
        ),
    ]
